name: testandbuild
on:
  push:
    branches:
      - main

jobs:
  # job 1
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: test
        id: run-test
        run: go test ./... > TestResults.log
      - name: Upload Go test results
        if: failure() && steps.run-test.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: TestResults.log

  # job2
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: build
        run: go build -o tester .
