name: testandbuild
on:
  push:
    branches:
      - main

jobs:
  # job 1
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: test
        run: go test ./... -json > TestResults.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults.json
          path: TestResults.json

  # job2
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: build
        run: go build -o tester .
