name: testandbuild
on:
  push:
    branches:
      - main

jobs:
  # job 1
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Display Go version
        run: go version

  # # job2
  # build:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - name: startup
  #       run: echo "starting up build"
  #     - name: get code
  #       uses: actions/checkout@v3
  #     - name: build
  #       run: go build -o tester .
